# Generated by Django 2.1.2 on 2018-12-10 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(default='None')),
                ('image', models.TextField(default='https://images.unsplash.com/photo-1531988042231-d39a9cc12a9a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=a562d48d64fd49e7cd0419f70806d696&auto=format&fit=crop&w=750&q=80')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('borrower_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(default='None')),
                ('image', models.TextField(default='https://images.unsplash.com/photo-1522165078649-823cf4dbaf46?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=756f069c98c96a701453b1e27630e961&auto=format&fit=crop&w=750&q=80')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('borrower_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('borrower', models.IntegerField(null=True)),
                ('admin', models.IntegerField(null=True)),
                ('message', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_type', models.CharField(default='none', max_length=20)),
                ('eventname', models.TextField(default=' ')),
                ('quantity', models.IntegerField(default=0)),
                ('date_application', models.DateField(auto_now_add=True)),
                ('year', models.IntegerField(default=2018)),
                ('month', models.IntegerField(default=0)),
                ('start_day', models.IntegerField(default=0)),
                ('end_day', models.IntegerField(default=0)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('remarks', models.TextField(default='none')),
                ('status', models.IntegerField(default=0)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Borrower')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=200)),
                ('day', models.IntegerField(default=1)),
                ('month', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2018)),
                ('time_start', models.IntegerField(default=6)),
                ('time_end', models.IntegerField(default=21)),
                ('item_type', models.IntegerField(default=0)),
                ('item_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Superadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=2000)),
                ('ttl', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('usertype', models.IntegerField(default=2)),
                ('token_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Token')),
            ],
        ),
        migrations.AddField(
            model_name='superadmin',
            name='token_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Token'),
        ),
        migrations.AddField(
            model_name='subadmin',
            name='token_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Token'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='token_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Token'),
        ),
    ]
