# Generated by Django 2.1.2 on 2018-12-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181210_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='borrower_id',
            new_name='borrower',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='item_id',
            new_name='item',
        ),
    ]
