# Generated by Django 2.1.2 on 2018-12-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181213_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='borrower_id',
            new_name='borrower',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='borrower_id',
            new_name='borrower',
        ),
    ]
