# Generated by Django 2.1.2 on 2018-12-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181213_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='borrower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='item',
            field=models.IntegerField(default=0),
        ),
    ]
