# Generated by Django 2.1.2 on 2018-12-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181213_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='borrower',
            new_name='borrower_id',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='borrower',
        ),
        migrations.AddField(
            model_name='equipment',
            name='borrower_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facility',
            name='borrower_id',
            field=models.IntegerField(default=0),
        ),
    ]
